[Variables]
;Zip code works here
WeatherCode=

;+ or - hours
TimeZoneOffset=-05

;F or C (I doubt K would work or be of any use)
Unit=F

;AIMP: PlayerName=AIMP
;foobar2000: PlayerName=CAD
;iTunes: PlayerName=iTunes
;J. River Media Center and Media Jukebox: PlayerName=CAD
;MediaMonkey: PlayerName=MediaMonkey
;MusicBee: PlayerName=CAD
;Winamp: PlayerName=Winamp
;VLC: PlayerName=CAD
;WMP: PlayerName=WMP
MusicPlayer=CAD

;Be sure to replace the @ symbol with %40
GoogleEmailAddress=

;Private string is the hash only
GooglePrivateString=
CalendarDaysAhead=30

;Hotbar Options
NumberOfBars=1
Path1=
Path2=
Path3=
Path4=
Path5=
Path6=
Path7=
Path8=
Path9=
